# Show config:
# tmux show -g

# Appearance
## colors
# normal
# code | fg      | bg
# 000  | black   | black
# 001  | maroon  | red
# 002  | green   | green
# 003  | olive   | orange
# 004  | navy    | blue
# 005  | purple  | purple
# 006  | teal    | cyan
# 007  | silver  | gray
# bright
# 008  | gray    | gray
# 009  | red     | red
# 010  | lime    | green
# 011  | yellow  | orange
# 012  | blue    | blue
# 013  | fuchsia | purple
# 014  | aqua    | cyan
# 015  | white   | gray

## windows
#set -g window-style 'fg=colour000,bg=colour007'
#set -g window-active-style 'fg=colour000,bg=colour007'

## borders
#set -g pane-border-style 'fg=colour000,bg=colour007'
#set -g pane-active-border 'fg=colour002,bg=colour007'

# system
# set -g default-terminal 'screen-256color'
set -g history-limit 10000
set -g mouse on
set -g mode-keys vi

set -g visual-activity on
set -g visual-bell on

set -g status 2
set -g status-style bg=default
set -g status-position top
set -g status-interval 30

set -g status-right-length 80
# set empty to append via -a
set -g  status-right ""
# available RAM
set -ag status-right " #[fg=colour008]#(free -h | head -n2 | tail -n1 | tr -s ' ' | cut -d ' ' -f3)#[fg=default]"
set -ag status-right " #(free -h | head -n2 | tail -n1 | tr -s ' ' | cut -d ' ' -f7)"
# battery
set -ag status-right " #(battery-real-percent)"
set -ag status-right " #[fg=default,bright]%a %F %H:%M"

# line 2
set -g status-format[1] " #(echo $TTY | cut -d / -f1,2 --complement) (#{pane_tty}) #{pane_current_path}"
# right side of second line
set -ag status-format[1] "#[align=right]"
set -ag status-format[1] "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"
set -ag status-format[1] "#{?#{==:#{host},#{pane_title}},, #{pane_title} }"
# set -g  status-right "#(ifconfig wlp0s20f3 | grep 'inet ' | tr -s '[:space:]' | cut -d ' ' -f3)"
#set -ag status-format[1] " #(sensors | grep -A2 cannonlake | tail -n 1 | cut -d ':' -f2 | tr -d ' ')"
#set -ag status-format[1] " #(sensors | grep -A2 acpitz-acpi-0 | tail -n 1 | tr -s ' ' | cut -d ' ' -f2)"

# key bindings
bind -N "Take screenshot" -n M-i run -b fbsc
