# for font use one of `kitty +list-fonts`
# for theme use `kitten themes --reload-in=all <Name>` and name from ~/.config/themes
# font_family      ComicShannsMono Nerd Font
font_family      family="Do"
font_size        23
# symbol_map U+3040-U+30FF Noto Sans Mono CJK JP
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape beam
cursor_stop_blinking_after 0.1

scrollback_lines 5000

repaint_delay 100
sync_to_monitor no

hide_window_decorations yes
background_opacity 0.8

# tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# shell_integration enabled
enable_audio_bell no
# bell_path /usr/share/sounds/freedesktop/stereo/bell.oga

visual_bell_duration 0.5
visual_bell_color #e5b566

# keymap tabs
map ctrl+page_down next_tab
map ctrl+page_up previous_tab
map ctrl+shift+page_up move_tab_backward
map ctrl+shift+page_down move_tab_forward
map ctrl+shift+d detach_tab
map ctrl+shift+t new_tab_with_cwd

# scroll
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map ctrl+shift+home scroll_home
map ctrl+shift+end scroll_end
map ctrl+shift+z scroll_to_prompt -1
map ctrl+shift+x scroll_to_prompt 1

# zoom
map ctrl+shift+plus change_font_size all +0.5
map ctrl+shift+equal change_font_size all +0.5
map ctrl+shift+minus change_font_size all -0.5
