#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

ln -sf ".xsettingsd-$1" ~/.xsettingsd
killall -HUP xsettingsd

gsettings set org.gnome.desktop.interface color-scheme "prefer-$1"

~/.config/rofi/set-color-scheme "$1"
~/.config/xrdb/set-color-scheme "$1"
# kitty reacts to gsettings
~/.config/fbterm/set-color-scheme "$1"

# enable-ipc = true. May not work
# polybar-msg cmd restart

pkill polybar
~/.config/polybar/toggle-free
