#!/bin/bash

SCHEME=$(ls -l ~/.xsettingsd | grep -oP '(?<=xsettingsd-)\w+')

if [[ -z $SCHEME ]]; then
    if [[ -n "$DISPLAY" ]]; then
        SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | grep -Po "(?<=prefer-)\w+")
    fi
fi

echo -n "$SCHEME"
