# American Silver
background            #d0d0d0
selection_foreground  #d0d0d0

# Raisin Black
foreground            #202020
cursor                #202020

color7                #202020
color15               #b5b5a5

# Trolley grey
selection_background  #707070

# gray
color0                #5a5a5a
color8                #6a6a6a

# Fiery rose (red)
color1                #ff5470
color9                #ff5470

# shade of yellow-green
color2                #97a470
color10               #a7c480

# Earth Yellow
color3                #e5b566
color11               #e5b566

# blue
color4                #3090a0
color12               #3090a0

# shade of magenta
color5                #b1769e
color13               #b1769e

# cyan
color6                #30a0a0
color14               #30a0a0
