# Raisin Black
background            #202020
selection_foreground  #202020

# American Silver
foreground            #d0d0d0
cursor                #d0d0d0
color7                #d0d0d0

# Trolley grey
selection_background  #808080

# Chinese Black
color0                #151515

# medium light shade of gray
color8                #a0a0a0

# Fiery rose (red)
color1                #ff5470
color9                #ff5470

# shade of yellow-green
color2                #97a470
color10               #97a470

# Earth Yellow
color3                #e5b566
color11               #e5b566

# Cerulean Frost (blue)
color4                #6c99ba
color12               #6c99ba

# shade of magenta
color5                #b1769e
color13               #b1769e

# Middle Blue Green (cyan)
color6                #7dd5cf
color14               #7dd5cf

# Cultured (whitesmoke)
color15               #f5f5f5
