#: black
color0 #1A1A1A
color8 #1A1A1A

#: red
color1 #D9D9A6
color9 #D9D9A6

#: green
color2  #70C270
color10 #70C270

#: blue
color4  #BEBEF4
color12 #BEBEF4

#: yellow
color3  #D9D9A6
color11 #D9D9A6

#: magenta
color5  #BEBEF4
color13 #BEBEF4

#: cyan
color6  #70C270
color14 #70C270

#: white
color7  #D9D9D9
color15 #D9D9D9
