#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )" || exit

cp -f --update=all ".Xresources-$1" ~/.Xresources

if [[ -n "$DISPLAY" ]]; then
    if [[ $(command -v xrdb) ]]; then
        xrdb -merge ~/.Xresources
    fi
fi
