map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream __REPLACE__-octane {
	server 127.0.0.1:8005 max_fails=1 fail_timeout=15s;
}

upstream __REPLACE__-fpm {
	# Gentoo way
	# /etc/php/fpm-php8.5/fpm.d/www.conf
	# server unix:/var/run/php-fpm-php8.5-www.sock;
	# Artix way
	# /etc/php/php-fpm.d/www.conf
	server unix:/run/php-fpm/php-fpm.sock;
}

server {
	listen 80;
	listen [::]:80;
	server_name __REPLACE__.test;
	server_tokens off;
	root /var/www/__REPLACE__/public;

	index index.php;

	access_log /var/log/nginx/__REPLACE__.access_log;
	error_log /var/log/nginx/__REPLACE__.error_log;

	location /index.php {
		try_files /not_exists @octane;
	}

	location / {
		try_files $uri $uri/ @octane;

		gzip_static on;
		expires 30d;
		add_header Cache-Control "public, immutable";
	}

	location = /favicon.ico {
		access_log off; log_not_found off;
	}
	location = /robots.txt {
		access_log off; log_not_found off;
	}

	error_page 404 /index.php;

	location @octane {
		set $suffix "";
 
		if ($uri = /index.php) {
			set $suffix ?$query_string;
		}

		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header Scheme $scheme;
		proxy_set_header SERVER_PORT $server_port;
		proxy_set_header REMOTE_ADDR $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		proxy_pass http://__REPLACE__-octane$suffix;

		proxy_connect_timeout 30s;

		proxy_read_timeout 30s;
		proxy_send_timeout 30s;

		# Buffering off for streaming responses
		proxy_buffering off;
		add_header X-Handler "Octane upstream" always;

		error_page 502 503 504 = @fpm;
	}

	location @fpm {
		include /etc/nginx/fastcgi_params;

		fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
		fastcgi_hide_header X-Powered-By;

		fastcgi_pass __REPLACE__-fpm;
		add_header X-Handler "PHP FPM upstream" always;
	}

	# Deny access to hidden files
	location ~ /\. {
		deny all;
	}
}
