#!/bin/bash

urlencode() {
    python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$1"
}

xkb-switch -s us

query=$(rofi -dmenu \
    -p "🔍 Google: " \
    -theme-str 'window {width: 70%; height: 2em;}' \
    -hide-scrollbar)

if [ -n "$query" ]; then
    encoded=$(urlencode "$query")
    ${BROWSER:-firefox} "https://www.google.com/search?q=$encoded"
fi
