#!/bin/bash

xkb-switch -s us

text=$(rofi -dmenu \
    -p "📝 Note: " \
    -theme-str 'window {width: 50%; height: 6em;}' \
    -hide-scrollbar)

if [ -n "$text" ]; then
    snote "$@" "$text" &
    # save memory on running bash instance
    detach
fi
