Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ru"
        #Option "XkbOptions" "grp:shift_caps_toggle,caps:escape"
        Option "XkbOptions" "grp:toggle,numpad:microsoft,shift:breaks_caps,misc:typo,compose:rwin"
	Option "AutoRepeat" "250 40"
EndSection

Section "InputClass"
        Identifier "Bluetooth Keyboard"
        MatchIsKeyboard "on"
	MatchProduct "Bluetooth 3.0 Keyboard"
        Option "XkbLayout" "us,ru"
        #Option "XkbOptions" "grp:shift_caps_toggle,grp_led:caps,caps:escape,altwin:swap_lalt_lwin"
	# delegate to kmonad
        Option "XkbOptions" "grp:toggle,grp_led:caps,numpad:microsoft,shift:breaks_caps,misc:typo,compose:rwin"
	Option "AutoRepeat" "250 40"
EndSection
