Section "Device"
        Identifier "Intel Graphics"

	# xf86-video-intel
        # Driver "intel"
	# mesa
        # Option "DRI" "iris"
        # Option "AccelMethod" "sna"

	Driver "modesetting"
        Option "DRI" "3"

	# no compositor
	# Option "TearFree" "true"

	Option      "TearFree"        "false"
	Option      "TripleBuffer"    "false"
	Option      "SwapbuffersWait" "false"

	Option "VSync" "false"

	# the entry under /sys/class/backlight to use
	Option "Backlight" "intel_backlight"
EndSection
