# see "man 4 libinput"
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "HorizontalScrolling" "true"
        Option "Tapping" "True"
        Option "ClickMethod" "clickfinger"
        Option "DisableWhileTyping" "False"
#        Option "ClickFinger2" "2"
#        Option "TapButton2" "2"
EndSection

Section "InputClass"
   Identifier     "Wheel Emulation"
   MatchIsPointer "on"
   Driver "libinput"
   Option         "EmulateWheelButton" "3"
   Option "EmulateWheel" "on"
   Option "HorizontalScrolling" "true"
EndSection
