# `equery uses picom` for opengl
# xrender, glx (opengl), xr_glx_hybrid.
backend = "glx";
# performance boost
glx-no-stencil=true;
# performance
glx-swap-method = 1;
vsync = true;
use-damage = true;

corner-radius = 18;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Code'",
  "class_g = 'Google-chrome'",
  "class_g = 'com.moonlight_stream.Moonlight'",
]

round-borders = 1;

shadow = false;
shadow-radius = 2;
shadow-opacity = 0.75
shadow-offset-x = 2;
shadow-offset-y = 2;

fading = true;
fade-in-step = 0.1;

inactive-opacity = 0.8;
frame-opacity = 0.4;
opacity-rule = [
  "100:class_g = 'TelegramDesktop'",
  "100:class_g = 'discord'",
  "100:class_g = 'Google-chrome'",
  "100:class_g = 'main.py'",
  "95:class_g = 'kitty'",
  "80:class_g = 'Gvim'",
]
