#!/bin/bash

base_dir="/home/$USER/git-repos/own/bash/bash-scripts/bin"

declare -a scripts=(
    "$base_dir/battery-real-percent monitor"
    "$base_dir/cpu-temp"
    "$base_dir/mem-free"
)
declare -a bars=(
    "battery"
    "heat"
    "memory"
)

arraylength=${#scripts[@]}

while [[ $(pgrep -x xinit) ]]; do
    for ((i = 0; i < arraylength; i++)); do
        script=${scripts[$i]}
        bar=${bars[$i]}
        if [[ -n "$(bash $script)" || -n "$1" ]]; then
            if ! pgrep -f -x "polybar $bar" >/dev/null; then
                polybar "$bar" & disown
            fi
        else
            if pgrep -f -x "polybar $bar" >/dev/null; then
                pkill -f -x "polybar $bar"
            fi
        fi
    done
    wait || exit
    sleep 10
done
