#!/bin/bash

base_dir="/home/$USER/git-repos/own/bash/bash-scripts/bin"

declare -a scripts=(
    "$base_dir/battery-real-percent monitor"
    "$base_dir/cpu-temp"
    "$base_dir/mem-free"
)
declare -a bars=(
    "battery"
    "heat"
    "memory"
)

PREVIOUS_DISPLAY=${DISPLAY}
PREVIOUS_DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}
PREVIOUS_ORIGINAL_XDG_CURRENT_DESKTOP=${ORIGINAL_XDG_CURRENT_DESKTOP}

unset DBUS_SESSION_BUS_ADDRESS
unset ORIGINAL_XDG_CURRENT_DESKTOP

# cron
export DISPLAY=':0'
export DBUS_SESSION_BUS_ADDRESS
export ORIGINAL_XDG_CURRENT_DESKTOP

arraylength=${#scripts[@]}
for ((i = 0; i < ${arraylength}; i++)); do
    script=${scripts[$i]}
    bar=${bars[$i]}
    if [[ -n "$(bash $script)" || -n $1 ]]; then
        if ! pgrep -f -x "polybar $bar" >/dev/null; then
            polybar $bar &
            disown
        fi
    else
        if pgrep -f -x "polybar $bar" >/dev/null; then
            pkill -f -x "polybar $bar"
        fi
    fi
done

DBUS_SESSION_BUS_ADDRESS=${PREVIOUS_DBUS_SESSION_BUS_ADDRESS}
ORIGINAL_XDG_CURRENT_DESKTOP=${PREVIOUS_ORIGINAL_XDG_CURRENT_DESKTOP}
DISPLAY=${PREVIOUS_DISPLAY}
