# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# added flags from cpuid2cpuflags
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3 bmi1 bmi2"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

MAKEOPTS="-j4"
USE="elogind -policykit X wayland xinerama gpm pulseaudio alsa gentoo-vm openssl dbus bluetooth fbcon"
# FEATURES="getbinpkg binpkg-request-signature"

GRUB_PLATFORMS="efi-64"
INPUT_DEVICES="libinput"
VIDEO_CARDS="intel iris"

# web
PHP_TARGETS="php8-4 php8-5"
APACHE2_MODULES="$APACHE2_MODULES http2 proxy proxy_http proxy_fcgi proxy_balancer slotmem_shm lbmethod_byrequests"
APACHE2_MPMS="event"
# see https://gitweb.gentoo.org/repo/gentoo.git/plain/profiles/desc/nginx_modules_http.desc
NGINX_MODULES_HTTP="$NGINX_MODULES_HTTP access fastcgi proxy gzip gzip_static rewrite map"

QEMU_USER_TARGETS="x86_64"
QEMU_SOFTMMU_TARGETS="aarch64 x86_64"
